Site/Controllers/AdminController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Site.Models;

namespace Site.Controllers
{
    public class AdminController : Controller
    {
        private readonly SiteDBContext _context;

        public AdminController(SiteDBContext context)
        {
            this._context = context;
        }

        public async Task<IActionResult> Index()
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("../Image/Unauthorized");
            }

            List<FileCategories> categoryList = await _context.FileCategories.ToListAsync<FileCategories>();
            return View(categoryList);
        }

        [HttpPost]
        public async Task<IActionResult> NewCategory()
        {
            FileCategories category = new FileCategories
            {
                CategoryLabel = Request.Form["categoryLabel"]
            };

            await _context.FileCategories.AddAsync(category);
            try
            {
                await _context.SaveChangesAsync();
                if (!Directory.Exists(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images", category.CategoryLabel)))
                {
                    Directory.CreateDirectory(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images", category.CategoryLabel));
                }
            }
            catch (Exception)
            {
                return View("../Shared/Error");
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCategory(int? Id)
        {
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images");
            List<Images> imgList = await _context.Images.Where<Images>(i => i.CategoryId == Id).ToListAsync<Images>();
            FileCategories oldCategory = await _context.FileCategories.FirstAsync<FileCategories>(c => c.CategoryId == Id);

            if (imgList.Count() > 0)
            {
                try
                {
                    foreach (Images img in imgList)
                    {
                        string oldPath = Path.Combine(path, oldCategory.CategoryLabel, img.ImgFileName);
                        var file = new FileInfo(oldPath);
                        file.MoveTo(Path.Combine(path, "No Category", img.ImgFileName));
                        img.CategoryId = 0;
                    }
                    Directory.Delete(Path.Combine(path, oldCategory.CategoryLabel));
                    _context.FileCategories.Remove(oldCategory);
                    await _context.SaveChangesAsync();
                }
                catch (Exception)
                {
                    return View("../Shared/Error");
                }
            }
            else
            {
                _context.FileCategories.Remove(oldCategory);
                Directory.Delete(Path.Combine(path, oldCategory.CategoryLabel));
                await _context.SaveChangesAsync();
            }

            List<FileCategories> categoryList = await _context.FileCategories.ToListAsync<FileCategories>();

            return RedirectToAction("Index", categoryList);
        }

        [HttpPost]
        public async Task<IActionResult> EditCategory()
        {
            string newLabel = Request.Form["newLabel"];
            int categoryId = Int32.Parse(Request.Form["categoryId"]);

            FileCategories category = await _context.FileCategories.FirstAsync<FileCategories>(i => i.CategoryId == categoryId);

            string oldPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images", category.CategoryLabel);
            string newPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images", newLabel);

            try
            {
                Directory.Move(oldPath, newPath);
                category.CategoryLabel = newLabel;
                _context.FileCategories.Update(category);
                await _context.SaveChangesAsync();
            }
            catch(Exception)
            {
                return View("../Shared/Error");
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> EditContactPage()
        {
            string text = Request.Form["text"];

            ContactText contactText = await _context.ContactText.FirstAsync(i => i.ID == 1);
            contactText.Text = text;
            _context.ContactText.Update(contactText);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

Site/Controllers/ImageController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System.Data.SqlTypes;
using Site.Models;
using Microsoft.Extensions.FileProviders;
using Microsoft.AspNetCore.Http;

namespace Site.Controllers
{
    public class ImageController : Controller
    {
        private readonly SiteDBContext _context;

        public ImageController(SiteDBContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            AllFilesViewModel model = new AllFilesViewModel
            {
                Images = await _context.Images.ToListAsync<Images>(),
                Files = await _context.Files.ToListAsync<Files>(),
                Categories = await _context.FileCategories.ToListAsync<FileCategories>(),
                FileFolders = await _context.Folders.ToListAsync<Folders>()
            };

            model.Categories = model.Categories.OrderBy<FileCategories, int>(i => i.CategoryId);
            model.Images = model.Images.OrderByDescending<Images, DateTime>(t => t.UploadedDate);
            model.Files = model.Files.OrderByDescending<Files, DateTime>(t => t.UploadedDate);

            return View(model);
            
        }

        [HttpPost]
        public IActionResult Upload(List<IFormFile> formFiles)
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            foreach (var file in Request.Form.Files)
            {
                var path = "";
                int index = file.FileName.IndexOf('.') + 1;
                string fileType = file.FileName.Substring(index).ToLower();

                int categoryId = Int32.Parse(Request.Form["categoryId"]);
                FileCategories category = _context.FileCategories.First<FileCategories>(c => c.CategoryId == categoryId);
                path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images", category.CategoryLabel, file.FileName);

                try
                {
                    Images img = new Images();
                    img.ImgFileName = file.FileName;
                    img.UploadedDate = DateTime.Now;
                    img.IsPublished = 0;
                    img.CategoryId = categoryId;

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        file.CopyTo(stream);
                    }

                    _context.Images.Add(img);
                }
                catch (IOException)
                {
                    return View("../Shared/Error");
                }

                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        /*
        [HttpGet]
        public async Task<IActionResult> LoadAllFiles()
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            AllFilesViewModel model = new AllFilesViewModel
            {
                Images = await _context.Images.ToListAsync<Images>(),
                Files = await _context.Files.ToListAsync<Files>(),
                Categories = await _context.FileCategories.ToListAsync<FileCategories>(),
                FileFolders = await _context.Folders.ToListAsync<Folders>()
            };

            model.Categories = model.Categories.OrderBy<FileCategories, int>(i => i.CategoryId);
            model.Images = model.Images.OrderByDescending<Images, DateTime>(t => t.UploadedDate);
            model.Files = model.Files.OrderByDescending<Files, DateTime>(t => t.UploadedDate);

            return View("AllFiles", model);
        } */

        public async Task<IActionResult> Delete(int? Id)
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            if (Id == null)
            {
                return NotFound();
            }
            var img = await _context.FindAsync<Images>(Id);
            if (img == null)
            {
                return NotFound();
            }
            FileCategories category = await _context.FileCategories.FirstAsync(c => c.CategoryId == img.CategoryId);
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images", category.CategoryLabel, img.ImgFileName);
            var fileInfo = new FileInfo(path);
            try
            {
                _context.Images.Remove(img);
                if (fileInfo.Exists)
                {
                    fileInfo.Delete();
                }
                await _context.SaveChangesAsync();
            }
            catch (Exception)
            {
                return View("../Shared/Error");
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Publish(int? Id)
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            if (Id == null)
            {
                return NotFound();
            }

            Images img = await _context.Images.FindAsync(Id);
            if (img == null)
            {
                return NotFound();
            }
            img.IsPublished = 1;
            img.PublishedDate = DateTime.Now;
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> SetImageAsStart(int? Id)
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            if (Id == null)
            {
                return NotFound();
            }

            Images img = await _context.Images.FindAsync(Id);
            if (img == null)
            {
                return NotFound();
            }

            img.StartImage = 1;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> RemoveImageAsStart(int? Id)
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            if (Id == null)
            {
                return NotFound();
            }

            Images img = await _context.Images.FindAsync(Id);
            if (img == null)
            {
                return NotFound();
            }

            img.StartImage = 0;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Unpublish(int? Id)
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            if (Id == null)
            {
                return NotFound();
            }

            Images img = await _context.Images.FindAsync(Id);
            if (img == null)
            {
                return NotFound();
            }
            img.IsPublished = 0;
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> CategoryUpdate(int? ImgId, int? CatId)
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            if (ImgId == null || CatId == null)
            {
                return NotFound();
            }

            var img = await _context.Images.FirstAsync<Images>(i => i.ImageId == ImgId);

            if (img == null)
            {
                return NotFound();
            }
            FileCategories newCategory = await _context.FileCategories.FirstAsync<FileCategories>(i => i.CategoryId == CatId);
            FileCategories oldCategory = await _context.FileCategories.FirstAsync<FileCategories>(i => i.CategoryId == img.CategoryId);
            img.CategoryId = (int)CatId;

            _context.Images.Update(img);

            try
            {
                using (var oldStream = new FileStream(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images", oldCategory.CategoryLabel, img.ImgFileName), FileMode.OpenOrCreate))
                {
                    using (var newStream = new FileStream(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images", newCategory.CategoryLabel, img.ImgFileName), FileMode.OpenOrCreate))
                    {
                        await oldStream.CopyToAsync(newStream);
                    }
                }

                System.IO.File.Delete(Path.Combine(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images", oldCategory.CategoryLabel, img.ImgFileName)));

                await _context.SaveChangesAsync();
            }
            catch (Exception)
            {
                return View("../Shared/Error", img);
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> UpdateDescription()
         {
            int imgId = Int32.Parse(Request.Form["imgId"]);
            string description = Request.Form["description_"+ imgId.ToString()];

            Images img = await _context.Images.FirstAsync<Images>(i => i.ImageId == imgId);
            img.Description = description;

Site/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Site.Models;

namespace Site.Controllers
{
    [Consumes("application/x-www-form-urlencoded")]
    public class UserController : Controller
    {
        private readonly SiteDBContext _context;

        public UserController(SiteDBContext context)
        {
            this._context = context;
        }

        [HttpPost]
        [Route("new")]
        public async Task<IActionResult> New(Users user)
        {
            SecurePassword psw = new SecurePassword();
            string PasswordSalt = psw.RandomSalt;
            string UserPassword = psw.GenerateSaltedHash(user.Password);

            await _context.Users.AddAsync(new Users
            {
                UserName = user.UserName,
                Email = user.Email,
                Password = UserPassword,
                PasswordSalt = PasswordSalt
            });

            await _context.SaveChangesAsync();
            HttpContext.Session.Set("Authenticated", new byte[1] { 1 });
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [Route("Verify")]
        public async Task<IActionResult> Verify(Users user)
        {
            if (!ModelState.IsValid)
            {
                return StatusCode(500, "Not a valid model");
            }

            SecurePassword psw = new SecurePassword();
            string submittedUserName = user.UserName;
            string submittedPassword = user.Password;
            try
            {
                Users userToVerify = await _context.Users.FirstOrDefaultAsync<Users>(u => u.UserName == user.UserName);
                if (user == null)
                {
                    return NoContent();
                }

                if (psw.VerifyPassword(submittedPassword, userToVerify.PasswordSalt, userToVerify.Password))
                {
                    HttpContext.Session.Set("Authenticated", new byte[1] { 1 });
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            catch (Exception)
            {
                return StatusCode(500);
            }
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            
            return RedirectToAction("Index", "Home");
        }
    }
}

Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]Ester Ganestam</title>

    <!-- Global site tag (gtag.js) - Google Analytics
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-141409995-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-141409995-1');
    </script> -->

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <script src="~/lib/jquery/dist/jquery.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div class="container text-center">
            <h1><a class="head-title" href="/">ESTER GANESTAM</a></h1>
        </div>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#menu-navbar" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div id="menu-navbar" class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @if (Context.Session.Keys.Contains<string>("Authenticated"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Start">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Image" asp-action="Index">My Files</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Start">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                            </li>
                        }
                    </ul>
                </div>
                <p class="alignRight nav-label">Menu</p>
            </div>
        </nav>
    </header>
        <div class="container-fluid">
            <!--<partial name="_CookieConsentPartial" />-->
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2019 - Daniel Åslund
            </div>
        </footer>

        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
            </script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
            </script>
        </environment>
        <script src="~/js/site.js" asp-append-version="true"></script>

        @RenderSection("Scripts", required: false)
    </body>
</html>