Site/Controllers/ImageController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System.Data.SqlTypes;
using Site.Models;
using Microsoft.Extensions.FileProviders;
using Microsoft.AspNetCore.Http;

namespace Site.Controllers
{
    public class ImageController : Controller
    {
        private readonly SiteDBContext _context;

        public ImageController(SiteDBContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            AllFilesViewModel model = new AllFilesViewModel
            {
                Images = await _context.Images.ToListAsync<Images>(),
                Files = await _context.Files.ToListAsync<Files>(),
                Categories = await _context.FileCategories.ToListAsync<FileCategories>(),
                FileFolders = await _context.Folders.ToListAsync<Folders>()
            };

            model.Categories = model.Categories.OrderBy<FileCategories, int>(i => i.CategoryId);
            model.Images = model.Images.OrderByDescending<Images, DateTime>(t => t.UploadedDate);
            model.Files = model.Files.OrderByDescending<Files, DateTime>(t => t.UploadedDate);

            return View(model);
            
        }

        [HttpPost]
        public IActionResult Upload(List<IFormFile> formFiles)
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            foreach (var file in Request.Form.Files)
            {
                var path = "";
                int index = file.FileName.IndexOf('.') + 1;
                string fileType = file.FileName.Substring(index).ToLower();

                int categoryId = Int32.Parse(Request.Form["categoryId"]);
                FileCategories category = _context.FileCategories.First<FileCategories>(c => c.CategoryId == categoryId);
                path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images", category.CategoryLabel, file.FileName);

                try
                {
                    Images img = new Images();
                    img.ImgFileName = file.FileName;
                    img.UploadedDate = DateTime.Now;
                    img.IsPublished = 0;
                    img.CategoryId = categoryId;

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        file.CopyTo(stream);
                    }

                    _context.Images.Add(img);
                }
                catch (IOException)
                {
                    return View("../Shared/Error");
                }

                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        /*
        [HttpGet]
        public async Task<IActionResult> LoadAllFiles()
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            AllFilesViewModel model = new AllFilesViewModel
            {
                Images = await _context.Images.ToListAsync<Images>(),
                Files = await _context.Files.ToListAsync<Files>(),
                Categories = await _context.FileCategories.ToListAsync<FileCategories>(),
                FileFolders = await _context.Folders.ToListAsync<Folders>()
            };

            model.Categories = model.Categories.OrderBy<FileCategories, int>(i => i.CategoryId);
            model.Images = model.Images.OrderByDescending<Images, DateTime>(t => t.UploadedDate);
            model.Files = model.Files.OrderByDescending<Files, DateTime>(t => t.UploadedDate);

            return View("AllFiles", model);
        } */

        public async Task<IActionResult> Delete(int? Id)
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            if (Id == null)
            {
                return NotFound();
            }
            var img = await _context.FindAsync<Images>(Id);
            if (img == null)
            {
                return NotFound();
            }
            FileCategories category = await _context.FileCategories.FirstAsync(c => c.CategoryId == img.CategoryId);
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images", category.CategoryLabel, img.ImgFileName);
            var fileInfo = new FileInfo(path);
            try
            {
                _context.Images.Remove(img);
                if (fileInfo.Exists)
                {
                    fileInfo.Delete();
                }
                await _context.SaveChangesAsync();
            }
            catch (Exception)
            {
                return View("../Shared/Error");
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Publish(int? Id)
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            if (Id == null)
            {
                return NotFound();
            }

            Images img = await _context.Images.FindAsync(Id);
            if (img == null)
            {
                return NotFound();
            }
            img.IsPublished = 1;
            img.PublishedDate = DateTime.Now;
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> SetImageAsStart(int? Id)
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            if (Id == null)
            {
                return NotFound();
            }

            Images img = await _context.Images.FindAsync(Id);
            if (img == null)
            {
                return NotFound();
            }

            img.StartImage = 1;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> RemoveImageAsStart(int? Id)
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            if (Id == null)
            {
                return NotFound();
            }

            Images img = await _context.Images.FindAsync(Id);
            if (img == null)
            {
                return NotFound();
            }

            img.StartImage = 0;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Unpublish(int? Id)
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            if (Id == null)
            {
                return NotFound();
            }

            Images img = await _context.Images.FindAsync(Id);
            if (img == null)
            {
                return NotFound();
            }
            img.IsPublished = 0;
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> CategoryUpdate(int? ImgId, int? CatId)
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            if (ImgId == null || CatId == null)
            {
                return NotFound();
            }

            var img = await _context.Images.FirstAsync<Images>(i => i.ImageId == ImgId);

            if (img == null)
            {
                return NotFound();
            }
            FileCategories newCategory = await _context.FileCategories.FirstAsync<FileCategories>(i => i.CategoryId == CatId);
            FileCategories oldCategory = await _context.FileCategories.FirstAsync<FileCategories>(i => i.CategoryId == img.CategoryId);
            img.CategoryId = (int)CatId;

            _context.Images.Update(img);

            try
            {
                using (var oldStream = new FileStream(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images", oldCategory.CategoryLabel, img.ImgFileName), FileMode.OpenOrCreate))
                {
                    using (var newStream = new FileStream(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images", newCategory.CategoryLabel, img.ImgFileName), FileMode.OpenOrCreate))
                    {
                        await oldStream.CopyToAsync(newStream);
                    }
                }

                System.IO.File.Delete(Path.Combine(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images", oldCategory.CategoryLabel, img.ImgFileName)));

                await _context.SaveChangesAsync();
            }
            catch (Exception)
            {
                return View("../Shared/Error", img);
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> UpdateDescription()
         {
            int imgId = Int32.Parse(Request.Form["imgId"]);
            string description = Request.Form["description_"+ imgId.ToString()];

            Images img = await _context.Images.FirstAsync<Images>(i => i.ImageId == imgId);
            img.Description = description;

Site/Controllers/MailController.cs
using System;
using System.IO;
using System.Net;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MailKit;
using MailKit.Net;
using MimeKit.Text;
using MimeKit;
using MailKit.Net.Smtp;
using Microsoft.Extensions.Options;
using System.Net.Http;
using Newtonsoft.Json.Linq;
using SiteML.Model;


namespace Site.Controllers
{
    public class MailController : Controller
    {
        private readonly IOptions<MailConfiguration> _mailConfig;

        private readonly string[] badWords = new string[]
        {
            "cunt",
            "bitch",
            "fucker",
            "hora",
            "slyna",
            "judejävel",
            "jävel",
            "horjävel",
            "kuksugare",
            "cocksucker",
            "cock",
            "sucker",
            "kuk",
            "sugare",
            "fitta"
        };
        public MailController(IOptions<MailConfiguration> mailConfig)
        {
            _mailConfig = mailConfig;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult InvalidMessage()
        {
            return View();
        }

        public async Task<bool> VerifyreCaptcha(string reCaptchaResponse)
        {
            HttpClient client = new HttpClient();
            string secretKey = _mailConfig.Value.captchaSecretKey;
            var content = new FormUrlEncodedContent(new[]
            {
                new KeyValuePair<string, string>("secret", secretKey),
                new KeyValuePair<string, string>("response", reCaptchaResponse)
            });

            var response = await client.PostAsync("https://www.google.com/recaptcha/api/siteverify", content);

            if (response.StatusCode != HttpStatusCode.OK)
            {
                return false;
            }

            string JSONResult = response.Content.ReadAsStringAsync().Result;
            dynamic JSONData = JObject.Parse(JSONResult);

            if (JSONData.success != "true")
            {
                return false;
            }

            return true;
        }

        public IActionResult Send()
        {
            /*
            string reCaptchaVerification = Request.Form["g-recaptcha-response"];

            if (await VerifyreCaptcha(reCaptchaVerification) != true)
            {
                return RedirectToAction("InvalidCaptcha");
            }
            */

            string bodyText = Request.Form["body"];
            string subject = Request.Form["subject"];
            string fromAddress = Request.Form["emailaddress"];

            var input = new ModelInput();
            input.SentimentText = bodyText;

            ModelOutput result = ConsumeModel.Predict(input);

            if (result.Prediction)
            {
                return RedirectToAction("SpamResponse");
            }

            string[] bodyWords = bodyText.Split(" ");
            string[] subjectWords = subject.Split(" ");

            foreach (string word in bodyWords)
            {
                foreach(string badWord in badWords)
                {
                    if(word.ToLower() == badWord)
                    {
                        return RedirectToAction("InvalidMessage");
                    }
                }
            }

            foreach (string word in subjectWords)
            {
                foreach(string badWord in badWords)
                {
                    if (word.ToLower() == badWord)
                    {
                        return RedirectToAction("InvalidMessage");
                    }
                }
            }

            var message = new MimeMessage();
            message.To.Add(new MailboxAddress("Inbox", _mailConfig.Value.Receiver));
            message.From.Add(new MailboxAddress("Inbox", _mailConfig.Value.SmtpUser));
            message.Subject = subject;
            message.Body = new TextPart(TextFormat.Html)
            {
                Text = bodyText + "<br /><br /> Sent from: " + fromAddress
            };

            using (var client = new SmtpClient())
            {
                client.Connect(_mailConfig.Value.SmtpServer, _mailConfig.Value.SmtpPort, true);
                client.Authenticate(_mailConfig.Value.SmtpUser, _mailConfig.Value.SmtpPassword);
                client.Send(message);
                client.Disconnect(true);
            }

            return RedirectToAction("Index");
        }

        public IActionResult InvalidCaptcha()
        {
            return View("InvalidCaptcha");
        }

        public IActionResult SpamResponse()
        {
            return View("SpamWarning");
        }
    }
}

Site/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Site.Models;

namespace Site.Controllers
{
    [Consumes("application/x-www-form-urlencoded")]
    public class UserController : Controller
    {
        private readonly SiteDBContext _context;

        public UserController(SiteDBContext context)
        {
            this._context = context;
        }

        [HttpPost]
        [Route("new")]
        public async Task<IActionResult> New(Users user)
        {
            SecurePassword psw = new SecurePassword();
            string PasswordSalt = psw.RandomSalt;
            string UserPassword = psw.GenerateSaltedHash(user.Password);

            await _context.Users.AddAsync(new Users
            {
                UserName = user.UserName,
                Email = user.Email,
                Password = UserPassword,
                PasswordSalt = PasswordSalt
            });

            await _context.SaveChangesAsync();
            HttpContext.Session.Set("Authenticated", new byte[1] { 1 });
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [Route("Verify")]
        public async Task<IActionResult> Verify(Users user)
        {
            if (!ModelState.IsValid)
            {
                return StatusCode(500, "Not a valid model");
            }

            SecurePassword psw = new SecurePassword();
            string submittedUserName = user.UserName;
            string submittedPassword = user.Password;
            try
            {
                Users userToVerify = await _context.Users.FirstOrDefaultAsync<Users>(u => u.UserName == user.UserName);
                if (user == null)
                {
                    return NoContent();
                }

                if (psw.VerifyPassword(submittedPassword, userToVerify.PasswordSalt, userToVerify.Password))
                {
                    HttpContext.Session.Set("Authenticated", new byte[1] { 1 });
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            catch (Exception)
            {
                return StatusCode(500);
            }
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            
            return RedirectToAction("Index", "Home");
        }
    }
}

Site/Views/Home/Contact.cshtml
@model Site.Models.ContactText;

<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<script type="text/javascript">

    function verifyInput() {

        var subject = $("#contactSubjectField");
        var body = $("#contactBodyField");
        var email = $("#contactEmailField");

        if (subject.val() === "" || body.val() === "" || email.val() === "") {

            if (subject.val() === "") {
                subject.addClass("alert-danger");
            }
            else {
                if (subject.hasClass("alert-danger")) {
                    subject.removeClass("alert-danger");
                }
            }
            if (body.val() === "") {
                body.addClass("alert-danger");
            } else {
                if (body.hasClass("alert-danger")) {
                    body.removeClass("alert-danger");
                }
            }
            if (email.val() === "") {
                email.addClass("alert-danger");
            } else {
                if (email.hasClass("alert-danger")) {
                    email.removeClass("alert-danger");
                }
            }
        } else if (subject.val() != "" && body.val() != "" && email.val() != "") {
            console.log("everything was ok");
            $("#mailForm").submit();
        }
    }

    function blurSubject() {
        console.log("blur fired on subject field");
        var subject = $("#contactSubjectField");
        if (subject.val() === "") {
            subject.addClass('alert-danger');
        }
        else {
            if (subject.hasClass('alert-danger')) {
                subject.removeClass('alert-danger');
            }
        }
    }

    function blurBody() {
        
        var body = $("#contactBodyField");
        if (body.val() === "") {
            body.addClass('alert-danger');
        }
        else {
            if (body.hasClass('alert-danger')) {
                body.removeClass('alert-danger');
            }
        }
    }

    function blurEmail() {
        
        var email = $("#contactEmailField");
        if (email.val() === "") {
            email.addClass('alert-danger');
        }
        else {
            if (email.hasClass('alert-danger')) {
                email.removeClass('alert-danger');
            }
        }
    }

</script>

<div class="container">
    <h1>Contact</h1>
    <div class="container text-center ">
        <p>@Model.Text</p>
        <form id="mailForm" method="post" asp-controller="Mail" asp-action="Send">
            <div class="form-group">
                <div class="form-row pb-2">
                    <input type="text" class="form-control col-6 offset-3" id="contactSubjectField" onblur="blurSubject()" name="subject" placeholder="Subject" />
                </div>
                <div class="form-row pb-2">
                    <textarea class="form-control pb-3" cols="25" rows="15" id="contactBodyField" onblur="blurBody()" name="body" placeholder="Your message"></textarea>
                </div>
                <div class="form-row pb-5">
                    <input type="text" class="form-control col-6 offset-3" id="contactEmailField" onblur="blurEmail()" name="emailaddress" placeholder="Your E-Mail Address" />
                </div>
                <div class="form-row pb-2">
                    <input class="btn btn-primary" type="button" id="sendMailBtn" onclick="verifyInput()" value="Send!" />
                </div>
            </div>
        </form>
    </div>
</div>

Site/Views/Home/Index.cshtml
@model Site.Models.AllFilesViewModel
@{
    var StartImages = Model.Images.ToList<Images>();
}
<script src="~/js/site.js"></script>

<div class="container-fluid">
    <div id="carouselControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="~/Images/@Model.Categories.First(i => i.CategoryId == StartImages[0].CategoryId).CategoryLabel/@StartImages[0].ImgFileName" alt="@StartImages[0].Description" />
            </div>
            @for (int i = 1; i < StartImages.Count; i++)
            {
                <div class="carousel-item">
                    <img class="d-block w-100 h-100" src="~/Images/@Model.Categories.First(id => id.CategoryId == StartImages[i].CategoryId).CategoryLabel/@StartImages[i].ImgFileName" alt="@StartImages[i].Description">
                </div>
            }
        </div>
        <a class="carousel-control-prev" href="#carouselControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="false"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="false"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

Site/Views/Home/Login.cshtml
@model Site.Models.Users

<div class="container">
    <form asp-action="Verify" asp-controller="User">
        <div class="form-group row">
            <label class="col-sm-1" for="UserName">Username:</label>
            <div class="col-sm-6">
                <input class="form-control" id="UserName" type="text" asp-for="UserName" />
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-1" for="Password">Password:</label>
            <div class="col-sm-6">
                <input class="form-control" id="Password" type="password" asp-for="Password">
            </div>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Login"/>
        </div>
    </form>
</div>

Site/Views/Home/Start.cshtml
@model Site.Models.AllFilesViewModel;
@{
    var publicImages = Model.Images.ToList<Images>();
}
<script src="~/js/site.js"></script>
<nav id="category-navbar" class="navbar navbar-left navbar-expand-sm navbar-toggleable-sm navbar-light">
    <button id="category-navbar-btn" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#category-navbar-content" aria-expanded="false" aria-label="Toggle Categories">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div id="category-navbar-content" class="navbar-collapse collapse flex-sm-row-reverse">
        <ul class="navbar-nav flex-grow-1">
            @foreach (FileCategories category in Model.Categories)
            {
                <li class="nav-item category-link">
                    <p><a class="nav-link text-dark" asp-controller="Home" asp-action="IndexCategory" asp-route-categoryId="@category.CategoryId">@category.CategoryLabel</a></p>
                </li>
            }
            <li class="nav-item category-link">
                <p><a class="nav-link text-dark" asp-controller="Home" asp-action="Start">All</a></p>
            </li>
        </ul>
    </div>
    <span class="alignRight nav-label">Categories</span>
</nav>

<div class="container-fluid">
    <div class="container">
        <div class="row">
            @foreach (Images img in publicImages)
            {
                <div class="card col-12 col-sm-6 col-lg-4 col-xl-4">
                    <div class="card-body">
                        <img data-caption="@img.Description" class="card-img" src="~/Images/@Model.Categories.First(c => c.CategoryId == img.CategoryId).CategoryLabel/@img.ImgFileName" alt="@img.ImgFileName" />
                    </div>
                    @if (Context.Session.Keys.Contains<string>("Authenticated"))
                    {
                        <form id="descriptionForm_@img.ImageId" asp-controller="Image" asp-action="UpdateDescription">
                            <input class="form-control pb-2" name="description_@img.ImageId" type="text" placeholder="@img.Description" />
                            <input name="imgId" type="hidden" value="@img.ImageId" />
                        </form>
                        <script>
                        var hasFired = false;
                        $("#descriptionForm_@img.ImageId :input").blur(function () {
                            if (!hasFired) {
                                hasFired = true;
                                $('#descriptionForm_@img.ImageId').submit();
                            }
                        });
                        </script>
                    }
                    else
                    {
                        <p>@img.Description</p>
                    }
                    <div class="card-footer">
                        <p style="font-size:10px;" class="alignLeft">@Model.Categories.First(c => c.CategoryId == img.CategoryId).CategoryLabel</p>
                        <p style="font-size:10px;" class="alignRight">@img.PublishedDate.Value.ToLongDateString()</p>
                    </div>
                </div>
            }
        </div>
        <div id="myModal" class="modal">
            <p id="modalCaption"></p>
            <span id="modalClose" class="close">&times;</span>
            <img class="modal-content rounded" id="modalImg" src="" alt="">
        </div>
    </div>
</div>