Site/Models/Images.cs
using System;
using System.Collections.Generic;

namespace Site.Models
{
    public partial class Images
    {
        public int ImageId { get; set; }
        public string ImgFileName { get; set; }
        public DateTime UploadedDate { get; set; }
        public DateTime? PublishedDate { get; set; }
        public int IsPublished { get; set; }
        public int CategoryId { get; set; }
        public string Description { get; set; }
        public int StartImage { get; set; }
    }
}

Site/Controllers/FileController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Site.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;

namespace Site.Controllers
{
    public class FileController : Controller
    {
        private readonly SiteDBContext _context;

        public FileController(SiteDBContext context)
        {
            this._context = context;
        }

        public async Task<IActionResult> Delete()
        {

            foreach (var key in Request.Form.Keys)
            {
                int Id = 0;
                Int32.TryParse(key, out Id);

                if (Id == 0)
                {
                    break;
                }

                var file = await _context.FindAsync<Files>(Id);

                if (file == null)
                {
                    return NotFound();
                }

                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Files", file.FileName);
                FileInfo info = new FileInfo(path);
                try
                {
                    _context.Files.Remove(file);
                    info.Delete();
                    await _context.SaveChangesAsync();
                }
                catch (Exception)
                {
                    return View("../Shared/Error");
                }
            }

            return RedirectToAction("Index", "Image");
        }

        public async Task<IActionResult> Upload(List<IFormFile> formFiles)
        {
            int folderId = Int32.Parse(Request.Form["folderId"]);
            Folders folder = await _context.Folders.FirstAsync(f => f.FolderId == folderId);

            foreach (var file in Request.Form.Files)
            {
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Files", folder.FolderName, file.FileName);

                try
                {
                    Files newFile = new Files();
                    newFile.FileName = file.FileName;
                    newFile.FolderId = folderId;
                    newFile.UploadedDate = DateTime.Now;

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }

                    await _context.Files.AddAsync(newFile);
                    await _context.SaveChangesAsync();
                }
                catch (IOException)
                {
                    return View("../Shared/Error");
                }
            }

            return RedirectToAction("Index", "Image");
        }

        [HttpPost]
        public async Task<IActionResult> NewFolder()
        {
            var name = Request.Form["folderName"];
            var rootPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Files");
            Folders newFolder = new Folders{ FolderName = name };

            if (!Directory.Exists(Path.Combine(rootPath, name)))
            {
                try
                {
                    Directory.CreateDirectory(Path.Combine(rootPath, name));
                    _context.Folders.Add(newFolder);
                    await _context.SaveChangesAsync();
                }
                catch (Exception)
                {
                    return View("../Shared/Error");
                }
            }

            return RedirectToAction("Index", "Image");
        }

        public async Task<IActionResult> DeleteFolder(int? id)
        {
            
            Folders folder = _context.Folders.First(f => f.FolderId == id);

            try
            {
                _context.Folders.Remove(folder);
                Directory.Delete(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Files", folder.FolderName), true);
                await _context.SaveChangesAsync();
            }
            catch (Exception)
            {
                return View("../Shared/Error");
            }

            return RedirectToAction("Index", "Image");
        }
    }
}

Site/Controllers/ImageController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System.Data.SqlTypes;
using Site.Models;
using Microsoft.Extensions.FileProviders;
using Microsoft.AspNetCore.Http;

namespace Site.Controllers
{
    public class ImageController : Controller
    {
        private readonly SiteDBContext _context;

        public ImageController(SiteDBContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            AllFilesViewModel model = new AllFilesViewModel
            {
                Images = await _context.Images.ToListAsync<Images>(),
                Files = await _context.Files.ToListAsync<Files>(),
                Categories = await _context.FileCategories.ToListAsync<FileCategories>(),
                FileFolders = await _context.Folders.ToListAsync<Folders>()
            };

            model.Categories = model.Categories.OrderBy<FileCategories, int>(i => i.CategoryId);
            model.Images = model.Images.OrderByDescending<Images, DateTime>(t => t.UploadedDate);
            model.Files = model.Files.OrderByDescending<Files, DateTime>(t => t.UploadedDate);

            return View(model);
            
        }

        [HttpPost]
        public IActionResult Upload(List<IFormFile> formFiles)
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            foreach (var file in Request.Form.Files)
            {
                var path = "";
                int index = file.FileName.IndexOf('.') + 1;
                string fileType = file.FileName.Substring(index).ToLower();

                int categoryId = Int32.Parse(Request.Form["categoryId"]);
                FileCategories category = _context.FileCategories.First<FileCategories>(c => c.CategoryId == categoryId);
                path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images", category.CategoryLabel, file.FileName);

                try
                {
                    Images img = new Images();
                    img.ImgFileName = file.FileName;
                    img.UploadedDate = DateTime.Now;
                    img.IsPublished = 0;
                    img.CategoryId = categoryId;

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        file.CopyTo(stream);
                    }

                    _context.Images.Add(img);
                }
                catch (IOException)
                {
                    return View("../Shared/Error");
                }

                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        /*
        [HttpGet]
        public async Task<IActionResult> LoadAllFiles()
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            AllFilesViewModel model = new AllFilesViewModel
            {
                Images = await _context.Images.ToListAsync<Images>(),
                Files = await _context.Files.ToListAsync<Files>(),
                Categories = await _context.FileCategories.ToListAsync<FileCategories>(),
                FileFolders = await _context.Folders.ToListAsync<Folders>()
            };

            model.Categories = model.Categories.OrderBy<FileCategories, int>(i => i.CategoryId);
            model.Images = model.Images.OrderByDescending<Images, DateTime>(t => t.UploadedDate);
            model.Files = model.Files.OrderByDescending<Files, DateTime>(t => t.UploadedDate);

            return View("AllFiles", model);
        } */

        public async Task<IActionResult> Delete(int? Id)
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            if (Id == null)
            {
                return NotFound();
            }
            var img = await _context.FindAsync<Images>(Id);
            if (img == null)
            {
                return NotFound();
            }
            FileCategories category = await _context.FileCategories.FirstAsync(c => c.CategoryId == img.CategoryId);
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images", category.CategoryLabel, img.ImgFileName);
            var fileInfo = new FileInfo(path);
            try
            {
                _context.Images.Remove(img);
                if (fileInfo.Exists)
                {
                    fileInfo.Delete();
                }
                await _context.SaveChangesAsync();
            }
            catch (Exception)
            {
                return View("../Shared/Error");
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Publish(int? Id)
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            if (Id == null)
            {
                return NotFound();
            }

            Images img = await _context.Images.FindAsync(Id);
            if (img == null)
            {
                return NotFound();
            }
            img.IsPublished = 1;
            img.PublishedDate = DateTime.Now;
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> SetImageAsStart(int? Id)
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            if (Id == null)
            {
                return NotFound();
            }

            Images img = await _context.Images.FindAsync(Id);
            if (img == null)
            {
                return NotFound();
            }

            img.StartImage = 1;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> RemoveImageAsStart(int? Id)
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            if (Id == null)
            {
                return NotFound();
            }

            Images img = await _context.Images.FindAsync(Id);
            if (img == null)
            {
                return NotFound();
            }

            img.StartImage = 0;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Unpublish(int? Id)
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            if (Id == null)
            {
                return NotFound();
            }

            Images img = await _context.Images.FindAsync(Id);
            if (img == null)
            {
                return NotFound();
            }
            img.IsPublished = 0;
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> CategoryUpdate(int? ImgId, int? CatId)
        {
            if (!HttpContext.Session.Keys.Contains<string>("Authenticated"))
            {
                return View("Unauthorized");
            }

            if (ImgId == null || CatId == null)
            {
                return NotFound();
            }

            var img = await _context.Images.FirstAsync<Images>(i => i.ImageId == ImgId);

            if (img == null)
            {
                return NotFound();
            }
            FileCategories newCategory = await _context.FileCategories.FirstAsync<FileCategories>(i => i.CategoryId == CatId);
            FileCategories oldCategory = await _context.FileCategories.FirstAsync<FileCategories>(i => i.CategoryId == img.CategoryId);
            img.CategoryId = (int)CatId;

            _context.Images.Update(img);

            try
            {
                using (var oldStream = new FileStream(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images", oldCategory.CategoryLabel, img.ImgFileName), FileMode.OpenOrCreate))
                {
                    using (var newStream = new FileStream(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images", newCategory.CategoryLabel, img.ImgFileName), FileMode.OpenOrCreate))
                    {
                        await oldStream.CopyToAsync(newStream);
                    }
                }

                System.IO.File.Delete(Path.Combine(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images", oldCategory.CategoryLabel, img.ImgFileName)));

                await _context.SaveChangesAsync();
            }
            catch (Exception)
            {
                return View("../Shared/Error", img);
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> UpdateDescription()
         {
            int imgId = Int32.Parse(Request.Form["imgId"]);
            string description = Request.Form["description_"+ imgId.ToString()];

            Images img = await _context.Images.FirstAsync<Images>(i => i.ImageId == imgId);
            img.Description = description;

Site/Views/Image/Index.cshtml
@model Site.Models.AllFilesViewModel

<div class="container">

    <h4>File Repository</h4>
    <p>
        <a class="btn btn-primary" data-toggle="collapse" href="#imageDiv" role="button" aria-expanded="false" aria-controls="imageDiv">Images</a>
    </p>
    
    <div class="container collapse" id="imageDiv">
        @foreach (FileCategories category in Model.Categories)
        {
            <div class="row">
                <div class="col">
                    <p class="pt-3">
                        <a class="btn btn-secondary" data-toggle="collapse" href="#@category.CategoryLabel.Replace(" ", "")" role="button" aria-expanded="false" aria-controls="@category.CategoryLabel.Replace(" ", "")">
                            @category.CategoryLabel (@Model.Images.Where(i => i.CategoryId == category.CategoryId).Count())
                        </a>
                    </p>
                </div>
                <div class="col collapse" id="@category.CategoryLabel.Replace(" ", "")">
                    <form asp-controller="Image" asp-action="Upload" enctype="multipart/form-data" method="post">
                        <div class="row">
                            <div class="col">
                                <input class="custom-file-input" type="file" multiple name="files"/>
                                <label class="custom-file-label" for="uploadInput">Choose file(s)</label>
                            </div>
                            <div class="col">
                                <input type="submit" class="btn btn-primary" value="Upload" />
                                <input type="hidden" name="categoryId" value="@category.CategoryId" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="container collapse pb-3" id="@category.CategoryLabel.Replace(" ", "")">

                @if (Model.Images.Where<Images>(i => i.CategoryId == category.CategoryId).Count<Images>() < 1)
                {
                    <div class="row">
                        <p>No images in this category.</p>
                    </div>
                }

                @foreach (Images img in Model.Images.Where<Images>(i => i.CategoryId == category.CategoryId).ToList())
                {

                    <div class="row pt-3">
                        <div class="col-lg-8 col-md-5 col-sm-3">
                            <img src="~/Images/@category.CategoryLabel/@img.ImgFileName" alt="@img.ImgFileName" style="max-width:100%; height:auto" />
                            <p class="pt-1">Uploaded: @img.UploadedDate.ToString("yyyy'-'MM'-'dd")</p>
                            <a class="pr-2" asp-action="Delete" asp-controller="Image" asp-route-id="@img.ImageId">Delete</a>
                            @if (img.IsPublished == 1)
                            {
                                <a class="pr-2" asp-action="Unpublish" asp-controller="Image" asp-route-id="@img.ImageId">Unpublish</a>
                            }
                            else
                            {
                                <a class="pr-2" asp-action="Publish" asp-controller="Image" asp-route-id="@img.ImageId">Publish</a>
                            }
                            @if (img.StartImage == 1)
                            {
                                <a class="pr-2" asp-action="RemoveImageAsStart" asp-controller="Image" asp-route-id="@img.ImageId">Remove from start</a>
                            }
                            else
                            {
                                <a class="pr-2" asp-action="SetImageAsStart" asp-controller="Image" asp-route-id="@img.ImageId">Set as start image</a>
                            }
                            <button class="btn btn-secondary btn-outline-dark dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                @Model.Categories.First(c => c.CategoryId == img.CategoryId).CategoryLabel
                            </button>
                            <div class="dropdown-menu">
                                @foreach (FileCategories _category in Model.Categories)
                                {
                                    <a class="dropdown-item btn btn-secondary btn-outline-dark" asp-controller="Image" asp-action="CategoryUpdate" asp-route-ImgId="@img.ImageId" asp-route-CatId="@_category.CategoryId">@_category.CategoryLabel</a>
                                }
                            </div>
                        </div>
                    </div>
                }
            </div>
            <hr/>
        }
    </div>

    <p class="pt-3">
        <a class="btn btn-primary" data-toggle="collapse" href="#fileDiv" role="button" aria-expanded="false" aria-controls="fileDiv">Files</a>
    </p>
    <div class="container collapse" id="fileDiv">
        <div class="row">
            <form asp-controller="File" asp-action="NewFolder" method="post">
                <div class="col form-group">
                    <label for="folderName">New folder</label>
                    <input type="text" name="folderName" />
                    <input type="submit" class="btn btn-primary" value="Create" />
                </div>
            </form>
        </div>
        <hr/>
        
        @foreach (Folders folder in Model.FileFolders)
        {
        <div>
            <div class="row container pb-3">
                <div class="col">
                    <a class="btn btn-secondary" data-toggle="collapse" href="#@folder.FolderName.Replace(" ", "")" role="button" aria-expanded="false" aria-controls="@folder.FolderName.Replace(" ", "")">
                        @folder.FolderName (@Model.Files.Where(f => f.FolderId == folder.FolderId).Count())
                    </a>
                </div>
                <div class="col">
                    <a asp-controller="File" asp-action="DeleteFolder" class="btn btn-danger delete-folder-btn" data-folderid="@folder.FolderId">Delete Folder</a>
                </div>
            </div>

            <div class="container collapse" id="@folder.FolderName.Replace(" ", "")">

                <div class="col collapse" id="@folder.FolderName.Replace(" ", "")">
                    <form asp-controller="File" asp-action="Upload" enctype="multipart/form-data" method="post">
                        <div class="row">
                            <div class="col">
                                <input class="custom-file-input" type="file" multiple name="files" />
                                <label class="custom-file-label" for="uploadInput">Choose file(s)</label>
                            </div>
                            <div class="col">
                                <input type="submit" class="btn btn-primary" value="Upload" />
                                <input type="hidden" name="folderId" value="@folder.FolderId" />
                            </div>
                        </div>
                    </form>
                </div>

                @if (Model.Files.Where(f => f.FolderId == folder.FolderId).Count() == 0)
                {
                    <p class="pt-2">No files in this folder</p>
                }
                else
                {
                    <div class="container">
                        <form asp-controller="File" asp-action="Delete" enctype="multipart/form-data" method="post">
                            @foreach (Files file in Model.Files.Where(f => f.FolderId == folder.FolderId))
                            {
                                <div class="pt-3 form-group">
                                    <input type="checkbox" id="@file.FileId" name="@file.FileId" style="margin-right:5px;" />
                                    <label for="@file.FileId"><a class="text-dark" href="~/Files/@folder.FolderName/@file.FileName">@file.FileName</a></label>
                                </div>
                            }
                            <div class="form-group">
                                <input type="submit" class="btn btn-warning" value="Delete" />
                            </div>
                        </form>
                    </div>
                }
            </div>
            <hr/>
        </div>
        }
    </div>

    <div class="pt-3">
        <a class="btn btn-primary" asp-action="Index" asp-controller="Image">Back to submit</a>
    </div>
</div>

Site/Views/Image/Unauthorized.cshtml
@{
    ViewData["Title"] = "Unauthorized - ";
}
<div class="container">

    <h1>Unauthorized</h1>
    <h3>You have to login to access this page!</h3>
    <p>Please use <a href="/Home/Login">this page</a> to login</p>

</div>

Site/Views/Image/_Index.cshtml
@{
    ViewData["Title"] = "File Upload";
}

<div class="container">
    <h1>File Upload</h1>
</div>

<div class="container">
    <form method="post" asp-controller="Image" asp-action="Upload" enctype="multipart/form-data">
        <div class="input-group">
            <div class="custom-file">
                <input type="file" multiple name="files" class="custom-file-input" id="uploadInput"/>
                <label class="custom-file-label" for="uploadInput">Choose file(s)</label>
            </div>
        </div>
        <div class="form-group pt-3">
            <input type="submit" class="btn btn-primary" value="Upload"/>
        </div>
    </form>
</div>